export {default as Loading} from './Loading'
export {default as TopPart} from './TopPart'
export {default as RightPart} from './RightPart'
export {default as LeftPart} from './LeftPart'
export {default as MiddlePart} from './MiddlePart'